spring.application.name=Hospital-Managment-App

spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDB
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey=jhiuih73843iuehuh$&%^$G8238ybd823tt2biudwg87323gd
# application.properties
stripe.secret.key=sk_test_51SsOhcBWofEcT6tm9xHEWEhas6MIQN4BUSvFRA3NZsAujnPXREs7hFBh2l4XEdSXUrKWipK7QUBZW9sYeKUD2hVx00kuuJgk22
stripe.public.key=pk_test_51SsOhcBWofEcT6tmyxC2ffn0psnpyWWuX0OuVjjw6XGvdKIMxnkFup7AR8C8guRa5d5bQ6YGrGPnVIqJZn4qmGun001yQKyyOR
stripe.webhook.secret=whsec_lFrOBpy8y5EsovUXyXluRHlQshV3BUyz



hospital.open.time=09:00
hospital.close.time=21:00
